name: dartshelfserver
version: 0.0.1
description: A dart web server using the shelf package
environment:
    sdk: '>=2.10.0 < 3.0.0'

dependencies:
  args: 2.3.0
  shelf: 1.2.0

dev_dependencies:
  pedantic: ^1.10.0
